CREATE TABLE IF NOT EXISTS "test_table" (
"id" INTEGER PRIMARY KEY AUTOINCREMENT,
"int_field" INTEGER DEFAULT 0 NOT NULL,
"str_field" TEXT,
"bool_field" INTEGER NOT NULL DEFAULT 0,
"time_field" INTEGER NOT NULL DEFAULT 0,
"float_field" REAL NOT NULL DEFAULT 0.0
)^
CREATE TABLE IF NOT EXISTS "test_table_two" (
"id" INTEGER PRIMARY KEY AUTOINCREMENT,
"int_field" INTEGER DEFAULT 0 NOT NULL,
"str_field" TEXT,
"bool_field" INTEGER NOT NULL DEFAULT 0,
"time_field" INTEGER NOT NULL DEFAULT 0,
"float_field" REAL NOT NULL DEFAULT 0.0
)